// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnifhhknsswstbddgdjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuaWZoaGtuc3N3c3RiZGRnZGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODc0NzgsImV4cCI6MjA2NzY2MzQ3OH0.0-v1aB12swa0Ased1diNbiFCZ0WmXnnxrouwSoMPqck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});